spring:
  application:
    name: gateway

  cloud:
    gateway:
      httpclient:
        wiretap: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    web: debug
    org.springframework.cloud.gateway: debug